### Crear un nuevo record en el commit log (codificado en base64)
POST http://localhost:8080/record
Content-Type: application/json

{
    "value": "SGVsbG8gV29ybGQ="
}

### Obtener el record del commit log por su offset
GET http://localhost:8080/record/1
